export const skillsByCategory = {
  "Information Technology": [
    "Web Development",
    "Mobile App Development",
    "Database Management",
    "Cybersecurity",
    "Cloud Computing",
    "Machine Learning",
    "Data Science",
    "Networking",
    "UI/UX Design",
    "DevOps",
  ],
  "Business Administration": [
    "Strategic Planning",
    "Project Management",
    "Operations Management",
    "Financial Management",
    "Human Resource Management",
    "Marketing Management",
    "Supply Chain Management",
    "Business Analysis",
    "Quality Management",
    "Risk Management",
  ],
  Marketing: [
    "Digital Marketing",
    "Content Marketing",
    "Social Media Marketing",
    "Search Engine Optimization (SEO)",
    "Search Engine Marketing (SEM)",
    "Email Marketing",
    "Influencer Marketing",
    "Marketing Analytics",
    "Branding",
    "Public Relations",
  ],
  Finance: [
    "Financial Analysis",
    "Investment Management",
    "Financial Reporting",
    "Corporate Finance",
    "Financial Modeling",
    "Risk Management",
    "Auditing",
    "Taxation",
    "Accounting",
    "Budgeting",
  ],
  "Human Resources": [
    "Recruitment",
    "Employee Relations",
    "Training & Development",
    "Performance Management",
    "Compensation & Benefits",
    "HR Information Systems",
    "Labor Relations",
    "Talent Management",
    "Organizational Development",
    "Workforce Planning",
  ],
  Sales: [
    "Sales Strategy",
    "Customer Relationship Management (CRM)",
    "Sales Operations",
    "Sales Forecasting",
    "Negotiation",
    "Lead Generation",
    "Account Management",
    "Sales Analytics",
    "Cold Calling",
    "Presentation Skills",
  ],
  Engineering: [
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Software Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Environmental Engineering",
    "Industrial Engineering",
    "Materials Engineering",
  ],
  Healthcare: [
    "Medical Diagnosis",
    "Patient Care",
    "Healthcare Administration",
    "Nursing",
    "Pharmacy",
    "Public Health",
    "Health Informatics",
    "Health Education",
    "Medical Research",
    "Healthcare Quality Improvement",
  ],
  Education: [
    "Curriculum Development",
    "Instructional Design",
    "Educational Technology",
    "Classroom Management",
    "Student Assessment",
    "Special Education",
    "Adult Education",
    "Language Teaching",
    "Online Learning",
    "Educational Leadership",
  ],
};
